---

# 1 Initial Setup

# 2 Services

# 3 Network

# 4 Host Based Firewall

# 5 Access Control

# 5.1 Configure SSH Server

- name: 5.1.1 Ensure permissions on /etc/ssh/sshd_config are configured
  file:
    path: "/etc/ssh/{{ item.path }}"
    recurse: "{{ item.recurse }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - { path: sshd_config, recurse: false }
    - { path: sshd_config.d, recurse: true }

# 6 Logging and Auditing

# 7 System Maintenance
