---

# 1 Initial Setup

# 2 Services

# 3 Network

# 4 Host Based Firewall
- name: 4.1.1 Ensure ufw is installed
  apt:
    name: ufw
    state: present

- name: 4.1.2 Ensure iptables-persistent is not installed with ufw
  apt:
    name: iptables-persistent
    state: absent

- name: Allow SSH with ufw
  ufw:
    rule: allow
    from_ip: "{{ rpi_base_default_network }}"
    name: OpenSSH
  ignore_errors: "{{ ansible_check_mode }}"

- name: 4.1.3 Ensure ufw service is enabled
  ufw:
    state: enabled
  ignore_errors: "{{ ansible_check_mode }}"

- name: 4.1.4 Ensure ufw loopback traffic is configured (allow)
  ufw:
    rule: allow
    interface: lo
    direction: "{{ item }}"
  loop:
    - in
    - out

- name: 4.1.4 Ensure ufw loopback traffic is configured (deny)
  ufw:
    rule: deny
    from_ip: "{{ item }}"
  loop:
    - "127.0.0.0/8"
    - "::1"

- name: Allow default outgoing services
  ufw:
    rule: allow
    direction: out
    name: "{{ item }}"
  loop:
    - http
    - https
    - dns
    - ntp
  ignore_errors: "{{ ansible_check_mode }}"

- name: 4.1.7 Ensure ufw default deny firewall policy
  ufw:
    default: deny
    direction: "{{ item }}"
  loop:
    - incoming
    - outgoing
    - routed

# 4.2 Configure nftables - N/A

# 4.3 Configure iptables - N/A

# 5 Access Control

- name: 5.1 Configure SSH Server  # includes following items
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  notify: restart sshd
  # 5.1.1 Ensure permissions on /etc/ssh/sshd_config are configured
  # 5.1.1 Ensure permissions on /etc/ssh/sshd_config.d/*conf are configured - TODO
  # 5.1.2 Ensure permissions on SSH private host key files are configured - TODO
  # 5.1.3 Ensure permissions on SSH public host key files are configured - TODO
  # 5.1.4 Ensure sshd access is configured - TODO
  # 5.1.5 Ensure sshd Banner is configured - TODO
  # 5.1.6 Ensure sshd Ciphers are configured
  # 5.1.7 Ensure sshd ClientAliveInterval and ClientAliveCountMax are configured
  # 5.1.10 Ensure sshd HostbasedAuthentication is disabled
  # 5.1.11 Ensure sshd IgnoreRhosts is enabled
  # 5.1.12 Ensure sshd KexAlgorithms is configured
  # 5.1.13 Ensure sshd LoginGraceTime is configured
  # 5.1.14 Ensure sshd LogLevel is configured
  # 5.1.15 Ensure sshd MACs are configured
  # 5.1.16 Ensure sshd MaxAuthTries is configured
  # 5.1.17 Ensure sshd MaxSessions is configured
  # 5.1.18 Ensure sshd MaxStartups is configured
  # 5.1.19 Ensure sshd PermitEmptyPasswords is disabled
  # 5.1.20 Ensure sshd PermitRootLogin is disabled
  # 5.1.21 Ensure sshd PermitUserEnvironment is disabled
  # 5.1.22 Ensure sshd UsePAM is enabled - NOT?

# 6 Logging and Auditing

# 7 System Maintenance
