---

# 1 Initial Setup

# 1.7 Configure GNOME Display Manager - N/A

# 2 Services

- name: 2.2 Configure (uninstall) Client Services  # includes following items
  # 2.2.1 Ensure NIS Client is not installed
  # 2.2.2 Ensure rsh client is not installed
  # 2.2.3 Ensure talk client is not installed
  # 2.2.4 Ensure telnet client is not installed
  # 2.2.5 Ensure ldap client is not installed
  # 2.2.6 Ensure ftp client is not installed
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - nis
    - rsh-client
    - talk
    - telnet
    - ldap-utils
    - ftp

# 3 Network

# 3.1.1 Ensure IPv6 status is identified

# 3.1.2 Ensure wireless interfaces are disabled

# 3.1.3 Ensure bluetooth services are not in use

- name: 3.3 Configure Network Kernel Parameters  # includes following items
  # 3.3.1 Ensure ip forwarding is disabled
  # 3.3.2 Ensure packet redirect sending is disabled
  # 3.3.3 Ensure bogus icmp responses are ignored
  # 3.3.4 Ensure broadcast icmp requests are ignored
  # 3.3.5 Ensure icmp redirects are not accepted
  # 3.3.6 Ensure secure icmp redirects are not accepted
  # 3.3.7 Ensure reverse path filtering is enabled
  # 3.3.8 Ensure source routed packets are not accepted
  # 3.3.9 Ensure suspicious packets are logged
  # 3.3.10 Ensure tcp syn cookies is enabled
  # 3.3.11 Ensure ipv6 router advertisements are not accepted
  template:
    src: sysctl_ufw.conf.j2
    dest: /etc/ufw/sysctl.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart computer

# 4 Host Based Firewall
- name: 4.1.1 Ensure ufw is installed
  apt:
    name: ufw
    state: present

- name: 4.1.2 Ensure iptables-persistent is not installed with ufw
  apt:
    name: iptables-persistent
    state: absent

- name: Allow SSH with ufw
  ufw:
    rule: allow
    from_ip: "{{ rpi_base_default_network }}"
    name: OpenSSH
  ignore_errors: "{{ ansible_check_mode }}"

- name: 4.1.3 Ensure ufw service is enabled
  ufw:
    state: enabled
  ignore_errors: "{{ ansible_check_mode }}"

- name: 4.1.4 Ensure ufw loopback traffic is configured (allow)
  ufw:
    rule: allow
    interface: lo
    direction: "{{ item }}"
  loop:
    - in
    - out
  ignore_errors: "{{ ansible_check_mode }}"

- name: 4.1.4 Ensure ufw loopback traffic is configured (deny)
  ufw:
    rule: deny
    from_ip: "{{ item }}"
  loop:
    - "127.0.0.0/8"
    - "::1"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Allow default outgoing services (port)
  ufw:
    rule: allow
    direction: out
    port: "{{ item }}"
  loop:
    - http
    - https
    - ntp
  ignore_errors: "{{ ansible_check_mode }}"

- name: Allow default outgoing services (name)
  ufw:
    rule: allow
    direction: out
    name: "{{ item }}"
  loop:
    - dns
  ignore_errors: "{{ ansible_check_mode }}"

- name: 4.1.7 Ensure ufw default deny firewall policy
  ufw:
    default: deny
    direction: "{{ item }}"
  loop:
    - incoming
    - outgoing
    - routed
  ignore_errors: "{{ ansible_check_mode }}"

# 4.2 Configure nftables - N/A

# 4.3 Configure iptables - N/A

# 5 Access Control

- name: 5.1 Configure SSH Server  # includes following items
  # 5.1.1 Ensure permissions on /etc/ssh/sshd_config are configured
  # 5.1.1 Ensure permissions on /etc/ssh/sshd_config.d/*conf are configured - TODO
  # 5.1.2 Ensure permissions on SSH private host key files are configured - TODO
  # 5.1.3 Ensure permissions on SSH public host key files are configured - TODO
  # 5.1.4 Ensure sshd access is configured - TODO
  # 5.1.5 Ensure sshd Banner is configured - TODO
  # 5.1.6 Ensure sshd Ciphers are configured
  # 5.1.7 Ensure sshd ClientAliveInterval and ClientAliveCountMax are configured
  # 5.1.10 Ensure sshd HostbasedAuthentication is disabled
  # 5.1.11 Ensure sshd IgnoreRhosts is enabled
  # 5.1.12 Ensure sshd KexAlgorithms is configured
  # 5.1.13 Ensure sshd LoginGraceTime is configured
  # 5.1.14 Ensure sshd LogLevel is configured
  # 5.1.15 Ensure sshd MACs are configured
  # 5.1.16 Ensure sshd MaxAuthTries is configured
  # 5.1.17 Ensure sshd MaxSessions is configured
  # 5.1.18 Ensure sshd MaxStartups is configured
  # 5.1.19 Ensure sshd PermitEmptyPasswords is disabled
  # 5.1.20 Ensure sshd PermitRootLogin is disabled
  # 5.1.21 Ensure sshd PermitUserEnvironment is disabled
  # 5.1.22 Ensure sshd UsePAM is enabled - NOT?
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  notify: restart sshd

# 6 Logging and Auditing

# 7 System Maintenance
