---

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
  become: true

- name: exec locale-gen
  command:
    cmd: /usr/sbin/locale-gen
  become: true

- name: restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted
  become: true

- name: restart computer
  reboot:
  become: true
